Update server_status_client_debian

diff --git a/service/server_status_client_debian b/service/server_status_client_debian
--- a/service/server_status_client_debian
+++ b/service/server_status_client_debian
@@ -1,5 +1,4 @@
 #!/bin/bash
-
 ### BEGIN INIT INFO
 # Provides:          ServerStatus-Client
 # Required-Start:    $network $local_fs $remote_fs
@@ -18,7 +17,7 @@ if [[ -e "/usr/local/ServerStatus/client/status-client.py" ]]; then
 elif [[ -e "/usr/local/ServerStatus/status-client.py" ]]; then
 	BIN="/usr/local/ServerStatus/status-client.py"
 else
-	echo -e "${Error_font_prefix}[´íÎó]${Font_suffix} ¿Í»§¶ËÎÄ¼ş($NAME_BIN)ÕÒ²»µ½ !" && exit 1
+	echo -e "${Error_font_prefix}[é”™è¯¯]${Font_suffix} å®¢æˆ·ç«¯æ–‡ä»¶($NAME_BIN)æ‰¾ä¸åˆ° !" && exit 1
 fi
 RETVAL=0
 
@@ -32,15 +31,15 @@ check_running(){
 }
 do_start(){
 	if check_running; then
-	echo -e "${Info_font_prefix}[ĞÅÏ¢]${Font_suffix} $NAME (PID ${PID}) ÕıÔÚÔËĞĞ..." && exit 0
+	echo -e "${Info_font_prefix}[ä¿¡æ¯]${Font_suffix} $NAME (PID ${PID}) æ­£åœ¨è¿è¡Œ..." && exit 0
 	else
 		ulimit -n 51200 >/dev/null 2>&1
 		nohup python -u "$BIN" > /tmp/serverstatus_client.log 2>&1 &
 		sleep 2s
 		if check_running; then
-			echo -e "${Info_font_prefix}[ĞÅÏ¢]${Font_suffix} $NAME Æô¶¯³É¹¦ !"
+			echo -e "${Info_font_prefix}[ä¿¡æ¯]${Font_suffix} $NAME å¯åŠ¨æˆåŠŸ !"
 		else
-			echo -e "${Error_font_prefix}[´íÎó]${Font_suffix} $NAME Æô¶¯Ê§°Ü !"
+			echo -e "${Error_font_prefix}[é”™è¯¯]${Font_suffix} $NAME å¯åŠ¨å¤±è´¥ !"
 		fi
 	fi
 }
@@ -49,20 +48,20 @@ do_stop(){
 		kill -9 "${PID}"
 		RETVAL=$?
 		if [[ $RETVAL -eq 0 ]]; then
-			echo -e "${Info_font_prefix}[ĞÅÏ¢]${Font_suffix} $NAME Í£Ö¹³É¹¦ !"
+			echo -e "${Info_font_prefix}[ä¿¡æ¯]${Font_suffix} $NAME åœæ­¢æˆåŠŸ !"
 		else
-			echo -e "${Error_font_prefix}[´íÎó]${Font_suffix}$NAME Í£Ö¹Ê§°Ü !"
+			echo -e "${Error_font_prefix}[é”™è¯¯]${Font_suffix}$NAME åœæ­¢å¤±è´¥ !"
 		fi
 	else
-		echo -e "${Info_font_prefix}[ĞÅÏ¢]${Font_suffix} $NAME Î´ÔËĞĞ !"
+		echo -e "${Info_font_prefix}[ä¿¡æ¯]${Font_suffix} $NAME æœªè¿è¡Œ !"
 		RETVAL=1
 	fi
 }
 do_status(){
 	if check_running; then
-		echo -e "${Info_font_prefix}[ĞÅÏ¢]${Font_suffix} $NAME (PID ${PID}) ÕıÔÚÔËĞĞ..."
+		echo -e "${Info_font_prefix}[ä¿¡æ¯]${Font_suffix} $NAME (PID ${PID}) æ­£åœ¨è¿è¡Œ..."
 	else
-		echo -e "${Info_font_prefix}[ĞÅÏ¢]${Font_suffix} $NAME Î´ÔËĞĞ !"
+		echo -e "${Info_font_prefix}[ä¿¡æ¯]${Font_suffix} $NAME æœªè¿è¡Œ !"
 		RETVAL=1
 	fi
 }
@@ -75,7 +74,7 @@ case "$1" in
 	do_"$1"
 	;;
 	*)
-	echo "Ê¹ÓÃ·½·¨: $0 { start | stop | restart | status }"
+	echo "ä½¿ç”¨æ–¹æ³•: $0 { start | stop | restart | status }"
 	RETVAL=1
 	;;
 esac
